// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Problem struct {
	ID            string
	Title         string
	Description   string
	TimeLimitMs   int32
	MemoryLimitKb int32
	Difficulty    sql.NullString
	CreatedAt     sql.NullTime
}

type Submission struct {
	ID               string
	UserID           sql.NullString
	ProblemID        sql.NullString
	Code             string
	Language         string
	Status           sql.NullString
	PassedTestCases  sql.NullInt32
	TotalTestCases   sql.NullInt32
	Output           sql.NullString
	ExpectedOutput   sql.NullString
	Error            sql.NullString
	ExecutionTimeMs  sql.NullInt32
	MemoryUsedKb     sql.NullInt32
	Score            sql.NullInt32
	CodingStyleScore sql.NullInt32
	CreatedAt        sql.NullTime
}

type TestCase struct {
	ID             string
	ProblemID      sql.NullString
	Input          string
	ExpectedOutput string
	IsHidden       sql.NullBool
	CreatedAt      sql.NullTime
}

type User struct {
	ID           string
	Username     string
	PasswordHash string
	Email        sql.NullString
	Role         sql.NullString
	CreatedAt    sql.NullTime
}
