// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (id, title, difficulty, description, time_limit_ms, memory_limit_kb)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateProblemParams struct {
	ID            string
	Title         string
	Difficulty    sql.NullString
	Description   string
	TimeLimitMs   int32
	MemoryLimitKb int32
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createProblem,
		arg.ID,
		arg.Title,
		arg.Difficulty,
		arg.Description,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createSubmission = `-- name: CreateSubmission :exec
INSERT INTO submissions (id, problem_id, code, language, status, passed_test_cases, total_test_cases)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSubmissionParams struct {
	ID              string
	ProblemID       sql.NullString
	Code            string
	Language        string
	Status          sql.NullString
	PassedTestCases sql.NullInt32
	TotalTestCases  sql.NullInt32
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) error {
	_, err := q.db.ExecContext(ctx, createSubmission,
		arg.ID,
		arg.ProblemID,
		arg.Code,
		arg.Language,
		arg.Status,
		arg.PassedTestCases,
		arg.TotalTestCases,
	)
	return err
}

const createTestCase = `-- name: CreateTestCase :exec
INSERT INTO test_cases (id, problem_id, input, expected_output, is_hidden)
VALUES ($1, $2, $3, $4, $5)
`

type CreateTestCaseParams struct {
	ID             string
	ProblemID      sql.NullString
	Input          string
	ExpectedOutput string
	IsHidden       sql.NullBool
}

func (q *Queries) CreateTestCase(ctx context.Context, arg CreateTestCaseParams) error {
	_, err := q.db.ExecContext(ctx, createTestCase,
		arg.ID,
		arg.ProblemID,
		arg.Input,
		arg.ExpectedOutput,
		arg.IsHidden,
	)
	return err
}

const getCandidateScores = `-- name: GetCandidateScores :many
SELECT
    u.id        AS user_id,
    u.username,
    u.exam_started_at,
    COALESCE(SUM(s.score), 0)::int                                                AS total_score,
    COUNT(DISTINCT s.problem_id)::int                                             AS problems_attempted,
    COUNT(DISTINCT CASE WHEN s.status = 'Accepted' THEN s.problem_id END)::int   AS problems_accepted
FROM users u
LEFT JOIN submissions s ON u.id = s.user_id
WHERE u.role = 'candidate'
GROUP BY u.id, u.username, u.exam_started_at
ORDER BY total_score DESC
`

type GetCandidateScoresRow struct {
	UserID            string
	Username          string
	ExamStartedAt     sql.NullTime
	TotalScore        int32
	ProblemsAttempted int32
	ProblemsAccepted  int32
}

func (q *Queries) GetCandidateScores(ctx context.Context) ([]GetCandidateScoresRow, error) {
	rows, err := q.db.QueryContext(ctx, getCandidateScores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCandidateScoresRow
	for rows.Next() {
		var i GetCandidateScoresRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.ExamStartedAt,
			&i.TotalScore,
			&i.ProblemsAttempted,
			&i.ProblemsAccepted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestSubmissionByProblem = `-- name: GetLatestSubmissionByProblem :one
SELECT id, problem_id, code, language, status, passed_test_cases, total_test_cases, 
       COALESCE(output, '') as output, COALESCE(expected_output, '') as expected_output, COALESCE(error, '') as error
FROM submissions
WHERE problem_id = $1
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestSubmissionByProblemRow struct {
	ID              string
	ProblemID       sql.NullString
	Code            string
	Language        string
	Status          sql.NullString
	PassedTestCases sql.NullInt32
	TotalTestCases  sql.NullInt32
	Output          string
	ExpectedOutput  string
	Error           string
}

func (q *Queries) GetLatestSubmissionByProblem(ctx context.Context, problemID sql.NullString) (GetLatestSubmissionByProblemRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestSubmissionByProblem, problemID)
	var i GetLatestSubmissionByProblemRow
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Code,
		&i.Language,
		&i.Status,
		&i.PassedTestCases,
		&i.TotalTestCases,
		&i.Output,
		&i.ExpectedOutput,
		&i.Error,
	)
	return i, err
}

const getProblemByID = `-- name: GetProblemByID :one
SELECT id, title, difficulty, description FROM problems WHERE id = $1
`

type GetProblemByIDRow struct {
	ID          string
	Title       string
	Difficulty  sql.NullString
	Description string
}

func (q *Queries) GetProblemByID(ctx context.Context, id string) (GetProblemByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProblemByID, id)
	var i GetProblemByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Difficulty,
		&i.Description,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, problem_id, code, language, status, passed_test_cases, total_test_cases, 
       COALESCE(output, '') as output, COALESCE(expected_output, '') as expected_output, COALESCE(error, '') as error
FROM submissions
WHERE id = $1
`

type GetSubmissionByIDRow struct {
	ID              string
	ProblemID       sql.NullString
	Code            string
	Language        string
	Status          sql.NullString
	PassedTestCases sql.NullInt32
	TotalTestCases  sql.NullInt32
	Output          string
	ExpectedOutput  string
	Error           string
}

func (q *Queries) GetSubmissionByID(ctx context.Context, id string) (GetSubmissionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSubmissionByID, id)
	var i GetSubmissionByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Code,
		&i.Language,
		&i.Status,
		&i.PassedTestCases,
		&i.TotalTestCases,
		&i.Output,
		&i.ExpectedOutput,
		&i.Error,
	)
	return i, err
}

const getTestCasesByProblemID = `-- name: GetTestCasesByProblemID :many
SELECT id, input, expected_output FROM test_cases WHERE problem_id = $1 ORDER BY id ASC
`

type GetTestCasesByProblemIDRow struct {
	ID             string
	Input          string
	ExpectedOutput string
}

func (q *Queries) GetTestCasesByProblemID(ctx context.Context, problemID sql.NullString) ([]GetTestCasesByProblemIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getTestCasesByProblemID, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTestCasesByProblemIDRow
	for rows.Next() {
		var i GetTestCasesByProblemIDRow
		if err := rows.Scan(&i.ID, &i.Input, &i.ExpectedOutput); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblems = `-- name: ListProblems :many
SELECT id, title, difficulty, description FROM problems ORDER BY id ASC
`

type ListProblemsRow struct {
	ID          string
	Title       string
	Difficulty  sql.NullString
	Description string
}

func (q *Queries) ListProblems(ctx context.Context) ([]ListProblemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProblems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProblemsRow
	for rows.Next() {
		var i ListProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Difficulty,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissions = `-- name: ListSubmissions :many
SELECT id, problem_id, code, language, status, passed_test_cases, total_test_cases, 
       COALESCE(output, '') as output, COALESCE(expected_output, '') as expected_output, COALESCE(error, '') as error
FROM submissions
ORDER BY created_at DESC
`

type ListSubmissionsRow struct {
	ID              string
	ProblemID       sql.NullString
	Code            string
	Language        string
	Status          sql.NullString
	PassedTestCases sql.NullInt32
	TotalTestCases  sql.NullInt32
	Output          string
	ExpectedOutput  string
	Error           string
}

func (q *Queries) ListSubmissions(ctx context.Context) ([]ListSubmissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubmissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubmissionsRow
	for rows.Next() {
		var i ListSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Code,
			&i.Language,
			&i.Status,
			&i.PassedTestCases,
			&i.TotalTestCases,
			&i.Output,
			&i.ExpectedOutput,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByUserID = `-- name: ListSubmissionsByUserID :many
SELECT id, problem_id, language, status, passed_test_cases, total_test_cases, score, created_at
FROM submissions
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListSubmissionsByUserIDRow struct {
	ID              string
	ProblemID       sql.NullString
	Language        string
	Status          sql.NullString
	PassedTestCases sql.NullInt32
	TotalTestCases  sql.NullInt32
	Score           sql.NullInt32
	CreatedAt       sql.NullTime
}

func (q *Queries) ListSubmissionsByUserID(ctx context.Context, userID sql.NullString) ([]ListSubmissionsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubmissionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubmissionsByUserIDRow
	for rows.Next() {
		var i ListSubmissionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Language,
			&i.Status,
			&i.PassedTestCases,
			&i.TotalTestCases,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubmission = `-- name: UpdateSubmission :execrows
UPDATE submissions 
SET status = $1, 
    passed_test_cases = $2, 
    output = $3, 
    expected_output = $4, 
    error = $5
WHERE id = $6
`

type UpdateSubmissionParams struct {
	Status          sql.NullString
	PassedTestCases sql.NullInt32
	Output          sql.NullString
	ExpectedOutput  sql.NullString
	Error           sql.NullString
	ID              string
}

func (q *Queries) UpdateSubmission(ctx context.Context, arg UpdateSubmissionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSubmission,
		arg.Status,
		arg.PassedTestCases,
		arg.Output,
		arg.ExpectedOutput,
		arg.Error,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
