// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createSubmission = `-- name: CreateSubmission :exec
INSERT INTO submissions (id, problem_id, code, language, status, passed_test_cases, total_test_cases)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSubmissionParams struct {
	ID              string
	ProblemID       sql.NullString
	Code            string
	Language        string
	Status          sql.NullString
	PassedTestCases sql.NullInt32
	TotalTestCases  sql.NullInt32
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) error {
	_, err := q.db.ExecContext(ctx, createSubmission,
		arg.ID,
		arg.ProblemID,
		arg.Code,
		arg.Language,
		arg.Status,
		arg.PassedTestCases,
		arg.TotalTestCases,
	)
	return err
}

const getProblemByID = `-- name: GetProblemByID :one
SELECT id, title, difficulty, description FROM problems WHERE id = $1
`

type GetProblemByIDRow struct {
	ID          string
	Title       string
	Difficulty  sql.NullString
	Description string
}

func (q *Queries) GetProblemByID(ctx context.Context, id string) (GetProblemByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProblemByID, id)
	var i GetProblemByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Difficulty,
		&i.Description,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, problem_id, code, language, status, passed_test_cases, total_test_cases, 
       COALESCE(output, '') as output, COALESCE(expected_output, '') as expected_output, COALESCE(error, '') as error
FROM submissions
WHERE id = $1
`

type GetSubmissionByIDRow struct {
	ID              string
	ProblemID       sql.NullString
	Code            string
	Language        string
	Status          sql.NullString
	PassedTestCases sql.NullInt32
	TotalTestCases  sql.NullInt32
	Output          string
	ExpectedOutput  string
	Error           string
}

func (q *Queries) GetSubmissionByID(ctx context.Context, id string) (GetSubmissionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSubmissionByID, id)
	var i GetSubmissionByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Code,
		&i.Language,
		&i.Status,
		&i.PassedTestCases,
		&i.TotalTestCases,
		&i.Output,
		&i.ExpectedOutput,
		&i.Error,
	)
	return i, err
}

const listProblems = `-- name: ListProblems :many
SELECT id, title, difficulty, description FROM problems ORDER BY id ASC
`

type ListProblemsRow struct {
	ID          string
	Title       string
	Difficulty  sql.NullString
	Description string
}

func (q *Queries) ListProblems(ctx context.Context) ([]ListProblemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProblems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProblemsRow
	for rows.Next() {
		var i ListProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Difficulty,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissions = `-- name: ListSubmissions :many
SELECT id, problem_id, code, language, status, passed_test_cases, total_test_cases, 
       COALESCE(output, '') as output, COALESCE(expected_output, '') as expected_output, COALESCE(error, '') as error
FROM submissions
ORDER BY created_at DESC
`

type ListSubmissionsRow struct {
	ID              string
	ProblemID       sql.NullString
	Code            string
	Language        string
	Status          sql.NullString
	PassedTestCases sql.NullInt32
	TotalTestCases  sql.NullInt32
	Output          string
	ExpectedOutput  string
	Error           string
}

func (q *Queries) ListSubmissions(ctx context.Context) ([]ListSubmissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubmissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubmissionsRow
	for rows.Next() {
		var i ListSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Code,
			&i.Language,
			&i.Status,
			&i.PassedTestCases,
			&i.TotalTestCases,
			&i.Output,
			&i.ExpectedOutput,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubmission = `-- name: UpdateSubmission :execrows
UPDATE submissions 
SET status = $1, 
    passed_test_cases = $2, 
    output = $3, 
    expected_output = $4, 
    error = $5
WHERE id = $6
`

type UpdateSubmissionParams struct {
	Status          sql.NullString
	PassedTestCases sql.NullInt32
	Output          sql.NullString
	ExpectedOutput  sql.NullString
	Error           sql.NullString
	ID              string
}

func (q *Queries) UpdateSubmission(ctx context.Context, arg UpdateSubmissionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSubmission,
		arg.Status,
		arg.PassedTestCases,
		arg.Output,
		arg.ExpectedOutput,
		arg.Error,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
